-- MySQL Script generated by MySQL Workbench
-- 11/08/17 09:54:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `idPersona` VARCHAR(20) NOT NULL,
  `Persona_Nombre` VARCHAR(45) NOT NULL,
  `Persona_Apellido` VARCHAR(45) NOT NULL,
  `Persona_Genero` CHAR(1) NOT NULL,
  `Persona_Estatura` DOUBLE NOT NULL,
  `Persona_Edad` INT NULL,
  `Persona_Descripcion` VARCHAR(100) NULL,
  `Persona_Tes` VARCHAR(100) NULL,
  `Tipo_Sangre` CHAR(3) NULL,
  `Observacion` VARCHAR(100) NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paciente` (
  `idPaciente` INT NOT NULL,
  `idPersona` VARCHAR(20) NOT NULL,
  `Condicion_Llegada` VARCHAR(100) NOT NULL,
  `Ubicacion` VARCHAR(45) NULL,
  PRIMARY KEY (`idPaciente`),
  UNIQUE INDEX `idPersona_UNIQUE` (`idPersona` ASC),
  CONSTRAINT `idPersona`
    FOREIGN KEY (`idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `idEmpleado` INT NOT NULL,
  `idPersona` VARCHAR(20) NOT NULL,
  `Empleado_Cargo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEmpleado`),
  UNIQUE INDEX `idPersona_UNIQUE` (`idPersona` ASC),
  CONSTRAINT `idPersona`
    FOREIGN KEY (`idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ficha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ficha` (
  `idFicha` INT NOT NULL,
  `IdPaciente` INT NOT NULL,
  `IdEmpleado` INT NOT NULL,
  `Ficha_Fecha` DATE NOT NULL,
  `Estado_Paciente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFicha`, `IdPaciente`),
  INDEX `fk_Empleado_idx` (`IdEmpleado` ASC),
  INDEX `fk_Paciente_idx` (`IdPaciente` ASC),
  CONSTRAINT `fk_Empleado`
    FOREIGN KEY (`IdEmpleado`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Paciente`
    FOREIGN KEY (`IdPaciente`)
    REFERENCES `mydb`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Habitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Habitacion` (
  `idHabitacion` INT NOT NULL,
  `Habitacion_Numero` INT NOT NULL,
  `Habitacion_Area` VARCHAR(100) NOT NULL,
  `Disponible` CHAR(1) NULL,
  PRIMARY KEY (`idHabitacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Movimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Movimiento` (
  `idMovimiento` INT NOT NULL,
  `idFicha` INT NOT NULL,
  `idPaciente` INT NOT NULL,
  `idEmpleado` INT NOT NULL,
  `Movimiento_Fecha` DATE NOT NULL,
  `Movimiento_Descripcion` VARCHAR(100) NOT NULL,
  `idHabitacion` INT NULL,
  PRIMARY KEY (`idMovimiento`, `idFicha`, `idPaciente`),
  INDEX `fk_ficha_idx` (`idFicha` ASC, `idPaciente` ASC),
  INDEX `fk_empleado_2_idx` (`idEmpleado` ASC),
  INDEX `fk_Habitacion_idx` (`idHabitacion` ASC),
  CONSTRAINT `fk_ficha`
    FOREIGN KEY (`idFicha` , `idPaciente`)
    REFERENCES `mydb`.`Ficha` (`idFicha` , `IdPaciente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_empleado_2`
    FOREIGN KEY (`idEmpleado`)
    REFERENCES `mydb`.`Empleado` (`idEmpleado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Habitacion`
    FOREIGN KEY (`idHabitacion`)
    REFERENCES `mydb`.`Habitacion` (`idHabitacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
